### PR TITLE
Added spanish translation

### PR DESCRIPTION
**Pull request by okelet**

### CODE REVIEW

**Comment by philipl** [comment]
Looks fine, but could you fix the spansih -> spanish in the commit message. Thanks.

**Comment by okelet** [comment]
OK, title changed. Also updated header of es.po (it was copied from german translation, and it contained references to german and the german translator), and pushed to the same patch-1.

**Comment by okelet** [comment]
Sorry, closed wrongly. Reopened.

**Comment by philipl** [comment]
Merged manually. THanks!

**Pull request closed without merging**
