### PR TITLE
Add Russian translation

### PR DESCRIPTION
**Pull request by DoctorRover**
Add Russian translation. Tested on Ubuntu 14.10.

### CODE REVIEW

**Comment by philipl** [comment]
Looks good but can you please squash it into a single commit.

Thanks!

**Comment by DoctorRover** [comment]
> Looks good...
> Thanks!
You are welcome! :)

> ...but can you please squash it into a single commit.
If I only new how to do this... I've never worked with git...

**Comment by DoctorRover** [comment]
I close the request to submit the changes later in a single commit.

**Comment by philipl** [comment]
Thanks!

**Pull request closed without merging**
